#FROM microsoft/iis
#Azure doesn't like the latest version of Windows just yet..
FROM microsoft/windowsservercore:ltsc2016

#This is where we might do cool things like install virus scanning 
#or baselining tasks, but actualy do nothing...